name: Use Generate Release Notes Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  generate-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # ... Any steps to set up or build your project

      - name: Release Notes Creation
        id: release-notes
        uses: gableroux/generate-github-release-notes@v0.1.2
        with:
          repository: ${{ github.repository }}
          base_tag: 'v0.0.2'
          head_tag: 'v0.0.3'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Currently not detecting new contributors
          # auto_detect_new_contributors: 'false'
          use_compare_changelog: 'true'

      - name: Display Generated Notes
        run: echo "${{ steps.release-notes.outputs.notes }}"

      - name: Write to File
        run: echo "${{ steps.release-notes.outputs.notes }}" > release_notes.txt

      - name: Upload Release Notes
        uses: actions/upload-artifact@v4
        with:
          name: release_notes
          path: release_notes.txt
