name: Use Generate Release Notes Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  generate-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # ... Any steps to set up or build your project

      - name: Generate Release Notes
        uses: gableroux/generate-github-release-notes@v0.0.2
        with:
          repository: ${{ github.repository }}
          base_tag: ${{ github.event.release.tag_name }}
          head_tag: ${{ github.sha }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # ... Further steps depending on your workflow
