name: Use Generate Release Notes Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  generate-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # ... Any steps to set up or build your project

      - name: Generate Release Notes
        id: generate-notes
        uses: gableroux/generate-github-release-notes@v0.0.2
        with:
          repository: ${{ github.repository }}
          base_tag: 'v0.0.2'
          head_tag: ${{ github.sha }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Skipping new contributors for now
          # auto_detect_new_contributors: 'false'
          use_compare_changelog: 'true'

      - name: Print Release Notes
        run: echo "${{ steps.generate-notes.outputs.notes }}"

      - name: Write to File
        run: echo "${{ steps.generate-notes.outputs.notes }}" > release_notes.txt

      - name: Upload Release Notes
        uses: actions/upload-artifact@v2
        with:
          name: release_notes
          path: release_notes.txt
